### ISSUE TITLE
error when install the package

### ISSUE THREAD

**Issue by mohamedhussieen** [kreait/laravel-firebase#138]
Problem 1
    - lcobucci/jwt[4.1.0, ..., 4.2.x-dev] require ext-sodium * -> it is missing from your system. Install or enable PHP's sodium extension.
    - kreait/laravel-firebase 4.1.0 requires kreait/firebase-php ^6.0 -> satisfiable by kreait/firebase-php[6.0.0, ..., 6.x-dev].
    - kreait/firebase-php[6.0.0, ..., 6.x-dev] require lcobucci/jwt ^4.1 -> satisfiable by lcobucci/jwt[4.1.0, ..., 4.2.x-dev].
    - Root composer.json requires kreait/laravel-firebase ^4.1 -> satisfiable by kreait/laravel-firebase[4.1.0].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

any help please

**Comment by jeromegamez** [comment]
As the error message describes, you've got to make sure the sodium extension is enabled in your installation. There have been XAMPP users [experiencing similar problems](https://www.google.com/search?q=xampp+(sodium+OR+libsodium)).

Here's an approach on StackOverflow that seems to be helpful: https://stackoverflow.com/a/52670500/284325

Since this is not a problem directly related to this package, I'm sorry I can't provide further support.
