### ISSUE TITLE
Symfony response setContent() error

### ISSUE THREAD

**Issue by ebiboy2** [kreait/laravel-firebase#145]
I get this error `Symfony\\Component\\HttpFoundation\\Response::setContent(): Argument #1 ($content) must be of type ?string, Kreait\\Firebase\\Auth given, called in /home/david/Documents/myNotifyApp/vendor/laravel/framework/src/Illuminate/Http/Response.php on line 72` when i call `return $appAuth = Firebase::project('rabaflow-aecd0')->auth();`
All credentials are correct.
What could be wrong?

**Comment by jeromegamez** [comment]
Hey 👋 

it looks as if you're returning the Auth component in a Controller Action instead of a string, `view()` or `Response`, but this is the only information that I can extract from the error.

If you'd like me to make more than an uneducated guess, you'd have to share some code and what you're trying to achieve 🙏
