### ISSUE TITLE
Support for PHP 8 (/Laravel 9)

### ISSUE THREAD

**Issue by AspireOne** [kreait/laravel-firebase#179]
### Describe the feature you would like to see

Currently when running "composer require laravel-notification-channels/fcm", it errors with "- kreait/firebase-php[4.30.0, ..., 4.x-dev] require php ^7.0 -> your php version (8.0.28) does not satisfy that requirement"... Is it missing support for php 8?

**Comment by jeromegamez** [comment]
I don't maintain `laravel-notification-channels/fcm`, I think you should raise the issue there: https://github.com/laravel-notification-channels/fcm

Since the output you referenced mentions version 4.x of the SDK: yes, that version only supports PHP 7, but the current version of the SDK is 7.x, so 4.x is very outdated.

Make sure to require the latest versions of the notification channel package, you can check with `composer outdated` which dependencies are upgradable.
