### ISSUE TITLE
Upgrade the following libraries to the latest versions

### ISSUE THREAD

**Issue by alexweb** [kreait/laravel-firebase#184]
### Describe the feature you would like to see

Currently I had to downgrade the following libs in my project to install your library: 

 - Downgrading psr/http-message (2.0 => 1.1): Extracting archive
 - Downgrading guzzlehttp/promises (2.0.0 => 1.5.3): Extracting archive

Can we upgrade them?

**Comment by jeromegamez** [comment]
While `psr/http-message` 2.x will be generally supported by the SDK inter next release, it will not be installed due to `google/cloud-core` (https://github.com/googleapis/google-cloud-php-core/blob/main/composer.json) not (yet) supporting it.

Aside from that, downgrading the libraries you mentioned should not be a problem unless another library you're using drops support for the 1.x versions.

Nonetheless, I'll create a new release shortly.

**Comment by jeromegamez** [comment]
The latest release removes the `par/http-message` dependency, so this shouldn't be a blocker anymore.

I also proposed a PR to widen the version constraint in https://github.com/googleapis/google-cloud-php/pull/6338. This and https://github.com/googleapis/google-cloud-php/pull/6249 should enable you to upgrade the dependencies in your project 🤞🏻
