### ISSUE TITLE
 Call to undefined method Messaging::createMessaging()

### ISSUE THREAD

**Issue by diadal** [kreait/laravel-firebase#24]
try to make samples of Laravel calls none of this working 

`ymfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Kreait\Firebase\Messaging::createMessaging() `

```
$messaging =  app('firebase.messaging')->createMessaging();
        $message = CloudMessage::withTarget('token', $id)
                ->withNotification(Notification::create('testing', 'working ok'))
                ->withData(['test' => 'value']);

        $m = $messaging->send($message);

```

**Comment by jeromegamez** [comment]
```php
$messaging = app('firebase.messaging');
```

**Comment by diadal** [comment]
not working `Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App\Http\Controllers\CloudMessage' not found`

```

$messaging =  app('firebase.messaging');


        $message = CloudMessage::withTarget('token', $id)
                ->withNotification(Notification::create('testing', 'working ok'))
                ->withData(['test' => 'value']);

        $m = $messaging->send($message);

        return [$m];

``

**Comment by jeromegamez** [comment]
You didn‘t

```php
use Kreait\Firebase\Messaging\CloudMessage;
```

**Comment by diadal** [comment]
no am only following the readme file try make some little samples for laravel like this `use Kreait\Firebase\Messaging\CloudMessage;` 

<img width="922" alt="Screenshot 2020-02-24 at 08 28 37" src="https://user-images.githubusercontent.com/19895516/75134839-cc175b80-56df-11ea-8e0b-ba5158bcb4b6.png">

**Comment by diadal** [comment]
now this `Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App\Http\Controllers\Notification' not found `

**Comment by diadal** [comment]
please which of the Notification needed

**Comment by jeromegamez** [comment]
Please read the documentation at https://firebase-php.readthedocs.io/

How to create notifications (includes the use statement): https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#adding-a-notification

How to create cloud messages (includes the use statement): https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#getting-started

The only difference between the direct usage of the SDK and this package is that you don‘t need to invoke the SDK‘s factory to instantiate the components.

So, instead of writing 

```php
$messaging = (new Factory)->withServiceAccount('...')->createMessaging();
```

you can write

```php
$messaging = app('firebase.messaging');
```

The same with all other components. After that, you‘ll find everything you need in the docs linked above.

**Comment by diadal** [comment]
working now `use Kreait\Firebase\Messaging\Notification;` thanks for your time
