### ISSUE TITLE
notifications are not received despite 200 response code

### ISSUE THREAD

**Issue by rohitjalmi90** [kreait/laravel-firebase#56]
Hello All,

I am facing one critical issue. I am trying to send notification to multiple tokens but one at time in loop. I am getting code=200 as response but actual notifications are not received by mobile user.(This is happening with some of token from that list)

I checked sending notification from console to those tokens and that is getting delivered. But not when sent via code.

Any suggestion how I can go about this issue?

Having really bad time with this as all notifications are not getting delivered

**Comment by jeromegamez** [comment]
I'm afraid these messages seem have been lost by firebase then - if the API returns a 200 code in return, we have to assume that the message has been successfully delivered, and there's not much we can do code-wise.

Is there a reason why you are sending the messages one by one instead of doing a multicast (https://firebase-php.readthedocs.io/en/5.8.0/cloud-messaging.html#send-messages-to-multiple-devices-multicast)?

**Comment by wontone18** [comment]
I am also facing the same issue. Am not sure this package exactly working or not.

this is my test code

	```
$title = 'My Notification Title';
				$body = 'My Notification Body';
			//	$imageUrl = 'http://lorempixel.com/400/200/';

				$notification = Notification::fromArray([
					'title' => $title,
					'body' => $body,
				//	'image' => $imageUrl,
				]);

				$notification = Notification::create($title, $body);

				$changedNotification = $notification
					->withTitle('Changed title')
					->withBody('Changed body');
				//	->withImageUrl('http://lorempixel.com/200/400/');
					
					//return $notification;
					
					$topic = 'a-topic';

				$message = CloudMessage::withTarget('topic', $topic)
				->withNotification($notification) // optional
							//->withData($data) // optional
						;

				
		$messaging->send($message);
```

**Comment by jeromegamez** [comment]
Since you double-posted, let me double-answer 😅

https://github.com/kreait/laravel-firebase/issues/61#issuecomment-691654035

I'm closing this now because this is most likely nothing that can be fixed from the side of the Laravel package or SDK, but feel free to add further comments or share your findings. 🤞
