### ISSUE TITLE
notifications are not received 

### ISSUE THREAD

**Issue by wontone18** [kreait/laravel-firebase#61]
I am facing a issue with this package. Notification are showing it correctly processing but neither it coming in firebase notification list nor reaching the devices.

my test code is below

```php
<?php

$messaging = app('firebase.messaging');

$title = 'My Notification Title';
$body = 'My Notification Body';
//	$imageUrl = 'http://lorempixel.com/400/200/';

$notification = Notification::fromArray([
    'title' => $title,
    'body' => $body,
    //	'image' => $imageUrl,
]);

$notification = Notification::create($title, $body);

$changedNotification = $notification
    ->withTitle('Changed title')
    ->withBody('Changed body');
//	->withImageUrl('http://lorempixel.com/200/400/');

//return $notification;

$topic = 'a-topic';

$message = CloudMessage::withTarget('topic', $topic)
    ->withNotification($notification) // optional
    //->withData($data) // optional
;
$messaging->send($message);
```

**Comment by jeromegamez** [comment]
_I edited your code block for better readabilty._

I am quite confident that the package and its underlying library works. If you don't get an error it means that the Firebase API has received and accepted your message. Now, there are two possibilities where the issue lies:

1. Firebase has accepted the message but didn't deliver it. In that case, there's nothing we can do from our side of the interaction. If you're convinced that everything is correct code-wise, you should open a support ticket with Google (but only after checking (2) 😅)

2. The device that you expect to get notified is not subscribed to the topic you're sending the notification to. 

To check (2), you'll need the registration token of the device that you're testing with. For example, if you're using the Firebase Web Client, you can do this with [`firebase.messaging.getToken()`](https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#gettoken).

Once you have the token, you can get the topics it's subscribed to by inspecting the App instance as described at https://firebase-php.readthedocs.io/en/5.8.1/cloud-messaging.html#working-with-topic-subscriptions

```php
$messaging = app('firebase.messaging');

$appInstance = $messaging->getAppInstance('<registration token>');

/** @var \Kreait\Firebase\Messaging\TopicSubscriptions $subscriptions */
$subscriptions = $appInstance->topicSubscriptions();

foreach ($subscriptions as $subscription) {
    echo "{$subscription->registrationToken()} is subscribed to {$subscription->topic()}\n";
}
```
If the topic appears in that list, the device/registration token *is* subscribed to the topic, and you should proceed with (1).

If the topic doesn't appear in the list, your device is not subscribed to the topic and cannot receive a message sent to that topic. In this case: subscribe the device to the topic 😅

**Comment by wontone18** [comment]
Thanks, i will first fix this from my react native client. I have tested this with a another alternative code in that it works smoothly. Yes token id was missing in the above.

**Comment by jeromegamez** [comment]
I'm closing this now because this is most likely nothing that can be fixed from the side of the Laravel package or SDK, but feel free to add further comments or share your findings. 🤞
