### ISSUE TITLE
Unable to query by geolocation

### ISSUE THREAD

**Issue by dilipd636** [kreait/laravel-firebase#62]
I want to fetch records using geolocation. is there any way to query using geolocation. please help me to resolve this issue.

**Comment by jeromegamez** [comment]
The SDK has no out-of-the-box support for Geo Queries, it only provides a bridge to the official google/cloud-firestore library. I donMt know if Google's library has native support for them either.

Unfortunately I haven't worked with GeoPoints in Firestore yet, so I can't help you further.

Perhaps this Stack Overflow Link can give you a hint to the right direction: https://stackoverflow.com/questions/58791529/read-the-firestore-geopoint-object-in-php

Also, if you Search Gooogle for "GeoFire", you'll find implementations for GeoQueries, mostly for other programming languages, but perhaps you'll find something that can help.

I appreciate if you share your findings in further comments, so that others facing the same challenge can benefit from them 🤞🙏

**Comment by MI-Soft** [comment]
is there any solution for this issue?
