### ISSUE TITLE
cURL error 28

### ISSUE THREAD

**Issue by Marwan-amer** [kreait/laravel-firebase#74]
Kreait\Firebase\Exception\Database\DatabaseError cURL error 28: Failed to connect to oauth2.googleapis.com port 443

This problem appears and disappears

**Comment by jeromegamez** [comment]
https://curl.se/libcurl/c/libcurl-errors.html 

curl Error 28 is a connection timeout. If it happens sometimes and sometimes not, it's either the network connection of your environment or the remote host is not reachable, but unfortunately not this library (I say unfortunately because otherwise I could fix it :))
